### ISSUE TITLE
Unauthorized error while checking Multus availability

### ISSUE THREAD

**Issue by gatici** [canonical/oai-ran-du-k8s-operator#65]
### Bug Description

unit-du-0: 11:47:28 ERROR unit.du/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-du-0/charm/venv/lightkube/core/generic_client.py", line 235, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/juju/agents/unit-du-0/charm/venv/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

### To Reproduce

Deploy DU charm using https://canonical-charmed-oai-ran.readthedocs-hosted.com/en/latest/tutorials/getting_started/.

### Environment

Juju 3.5.5
Microk8s 1.31 classic
Multus is enabled using addon 
`microk8s addons repo add community https://github.com/canonical/microk8s-community-addons --reference feat/strict-fix-multus`

### Relevant log output

```shell
gatici@gaticipc:~/newtf$ juju debug-log  --replay --include du
unit-du-0: 11:42:10 INFO juju.cmd running containerAgent [3.5.5 1d21840563a55809580976df0b4880e03323bbb7 gc go1.23.3]
unit-du-0: 11:42:10 INFO juju.cmd.containeragent.unit start "unit"
unit-du-0: 11:42:10 INFO juju.worker.upgradesteps upgrade steps for 3.5.5 have already been run.
unit-du-0: 11:42:10 INFO juju.worker.probehttpserver starting http server on 127.0.0.1:65301
unit-du-0: 11:42:10 INFO juju.api connection established to "wss://controller-service.controller-microk8s-classic-localhost.svc.cluster.local:17070/model/042331b4-2d63-45cd-88d2-02ba56a86117/api"
unit-du-0: 11:42:10 INFO juju.worker.apicaller [042331] "unit-du-0" successfully connected to "controller-service.controller-microk8s-classic-localhost.svc.cluster.local:17070"
unit-du-0: 11:42:10 INFO juju.api connection established to "wss://controller-service.controller-microk8s-classic-localhost.svc.cluster.local:17070/model/042331b4-2d63-45cd-88d2-02ba56a86117/api"
unit-du-0: 11:42:10 INFO juju.worker.apicaller [042331] "unit-du-0" successfully connected to "controller-service.controller-microk8s-classic-localhost.svc.cluster.local:17070"
unit-du-0: 11:42:10 INFO juju.worker.migrationminion migration migration phase is now: NONE
unit-du-0: 11:42:10 INFO juju.worker.logger logger worker started
unit-du-0: 11:42:10 WARNING juju.worker.proxyupdater unable to set snap core settings [proxy.http= proxy.https= proxy.store=]: exec: "snap": executable file not found in $PATH, output: ""
unit-du-0: 11:42:10 INFO juju.worker.leadership du/0 promoted to leadership of du
unit-du-0: 11:42:10 INFO juju.worker.caasupgrader abort check blocked until version event received
unit-du-0: 11:42:10 INFO juju.worker.caasupgrader unblocking abort check
unit-du-0: 11:42:10 INFO juju.agent.tools ensure jujuc symlinks in /var/lib/juju/tools/unit-du-0
unit-du-0: 11:42:10 INFO juju.worker.uniter unit "du/0" started
unit-du-0: 11:42:10 INFO juju.worker.uniter resuming charm install
unit-du-0: 11:42:10 INFO juju.worker.uniter.charm downloading ch:amd64/jammy/oai-ran-du-k8s-48 from API server
unit-du-0: 11:42:10 INFO juju.downloader downloading from ch:amd64/jammy/oai-ran-du-k8s-48
unit-du-0: 11:42:10 INFO juju.downloader download complete ("ch:amd64/jammy/oai-ran-du-k8s-48")
unit-du-0: 11:42:10 INFO juju.downloader download verified ("ch:amd64/jammy/oai-ran-du-k8s-48")
unit-du-0: 11:42:30 INFO juju.worker.uniter hooks are retried true
unit-du-0: 11:42:30 INFO juju.worker.uniter found queued "install" hook
unit-du-0: 11:42:31 INFO unit.du/0.juju-log Running legacy hooks/install.
unit-du-0: 11:42:32 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:32 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions/du-f1-net "HTTP/1.1 404 Not Found"
unit-du-0: 11:42:32 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:32 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/api/v1/namespaces/ran/pods/du-0 "HTTP/1.1 200 OK"
unit-du-0: 11:42:32 INFO unit.du/0.juju-log Waiting for Multus to be ready
unit-du-0: 11:42:33 INFO juju.worker.uniter.operation ran "install" hook (via hook dispatching script: dispatch)
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: POST https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 201 Created"
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: NetworkAttachmentDefinition du-f1-net created
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: PATCH https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du?fieldManager=KubernetesClient "HTTP/1.1 200 OK"
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: Multus annotation added to du statefulset
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions/du-f1-net "HTTP/1.1 200 OK"
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/api/v1/namespaces/ran/pods/du-0 "HTTP/1.1 200 OK"
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions/du-f1-net "HTTP/1.1 200 OK"
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:34 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/api/v1/namespaces/ran/pods/du-0 "HTTP/1.1 200 OK"
unit-du-0: 11:42:35 INFO unit.du/0.juju-log fiveg_f1:2: Waiting for Multus to be ready
unit-du-0: 11:42:35 INFO juju.worker.uniter.operation ran "fiveg_f1-relation-created" hook (via hook dispatching script: dispatch)
unit-du-0: 11:42:35 INFO juju.worker.uniter found queued "leader-elected" hook
unit-du-0: 11:42:36 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:36 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions/du-f1-net "HTTP/1.1 200 OK"
unit-du-0: 11:42:36 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:36 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/api/v1/namespaces/ran/pods/du-0 "HTTP/1.1 200 OK"
unit-du-0: 11:42:36 INFO unit.du/0.juju-log Waiting for Multus to be ready
unit-du-0: 11:42:36 INFO juju.worker.uniter.operation ran "leader-elected" hook (via hook dispatching script: dispatch)
unit-du-0: 11:42:37 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:37 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions/du-f1-net "HTTP/1.1 200 OK"
unit-du-0: 11:42:37 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:37 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/api/v1/namespaces/ran/pods/du-0 "HTTP/1.1 200 OK"
unit-du-0: 11:42:37 INFO unit.du/0.juju-log Waiting for Multus to be ready
unit-du-0: 11:42:38 INFO juju.worker.uniter.operation ran "config-storage-attached" hook (via hook dispatching script: dispatch)
unit-du-0: 11:42:39 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:39 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:39 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:39 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:39 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/api/v1/namespaces/ran/pods/du-0 "HTTP/1.1 200 OK"
unit-du-0: 11:42:39 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:39 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:39 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/api/v1/namespaces/ran/pods/du-0 "HTTP/1.1 200 OK"
unit-du-0: 11:42:39 INFO unit.du/0.juju-log Waiting for Multus to be ready
unit-du-0: 11:42:39 INFO juju.worker.uniter.operation ran "config-changed" hook (via hook dispatching script: dispatch)
unit-du-0: 11:42:39 INFO juju.worker.uniter found queued "start" hook
unit-du-0: 11:42:41 INFO unit.du/0.juju-log Running legacy hooks/start.
unit-du-0: 11:42:42 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:42 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions/du-f1-net "HTTP/1.1 200 OK"
unit-du-0: 11:42:42 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:42 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/api/v1/namespaces/ran/pods/du-0 "HTTP/1.1 200 OK"
unit-du-0: 11:42:42 INFO unit.du/0.juju-log Waiting for Multus to be ready
unit-du-0: 11:42:42 INFO juju.worker.uniter.operation ran "start" hook (via hook dispatching script: dispatch)
unit-du-0: 11:42:43 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:43 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:43 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:43 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:43 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/api/v1/namespaces/ran/pods/du-0 "HTTP/1.1 200 OK"
unit-du-0: 11:42:43 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:43 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:43 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/api/v1/namespaces/ran/pods/du-0 "HTTP/1.1 200 OK"
unit-du-0: 11:42:43 INFO unit.du/0.juju-log fiveg_f1:2: Waiting for Multus to be ready
unit-du-0: 11:42:44 INFO juju.worker.uniter.operation ran "fiveg_f1-relation-changed" hook (via hook dispatching script: dispatch)
unit-du-0: 11:42:45 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:45 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions/du-f1-net "HTTP/1.1 200 OK"
unit-du-0: 11:42:45 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:45 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/api/v1/namespaces/ran/pods/du-0 "HTTP/1.1 200 OK"
unit-du-0: 11:42:45 INFO unit.du/0.juju-log fiveg_f1:2: Waiting for Multus to be ready
unit-du-0: 11:42:45 INFO juju.worker.uniter.operation ran "fiveg_f1-relation-joined" hook (via hook dispatching script: dispatch)
unit-du-0: 11:42:46 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:47 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:47 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:47 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:47 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/api/v1/namespaces/ran/pods/du-0 "HTTP/1.1 200 OK"
unit-du-0: 11:42:47 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 200 OK"
unit-du-0: 11:42:47 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/ran/statefulsets/du "HTTP/1.1 200 OK"
unit-du-0: 11:42:47 INFO unit.du/0.juju-log fiveg_f1:2: HTTP Request: GET https://10.152.183.1/api/v1/namespaces/ran/pods/du-0 "HTTP/1.1 200 OK"
unit-du-0: 11:42:47 INFO unit.du/0.juju-log fiveg_f1:2: Waiting for Multus to be ready
unit-du-0: 11:42:47 INFO juju.worker.uniter.operation ran "fiveg_f1-relation-changed" hook (via hook dispatching script: dispatch)
unit-du-0: 11:47:10 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 401 Unauthorized"
unit-du-0: 11:47:10 ERROR unit.du/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-du-0/charm/venv/lightkube/core/generic_client.py", line 235, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/juju/agents/unit-du-0/charm/venv/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-du-0/charm/lib/charms/kubernetes_charm_libraries/v0/multus.py", line 571, in multus_is_available
    list(
  File "/var/lib/juju/agents/unit-du-0/charm/venv/lightkube/core/generic_client.py", line 318, in list
    cont, chunk = self.handle_response("list", resp, br)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/lightkube/core/generic_client.py", line 251, in handle_response
    self.raise_for_status(resp)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/lightkube/core/generic_client.py", line 237, in raise_for_status
    raise transform_exception(e)
lightkube.core.exceptions.ApiError: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-du-0/charm/./src/charm.py", line 490, in <module>
    main(OAIRANDUOperator)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/__init__.py", line 343, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/_main.py", line 543, in main
    manager.run()
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/_main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/_main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/_main.py", line 134, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/framework.py", line 857, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-du-0/charm/./src/charm.py", line 161, in _configure
    if not self._kubernetes_multus.multus_is_available():
  File "/var/lib/juju/agents/unit-du-0/charm/lib/charms/kubernetes_charm_libraries/v0/multus.py", line 765, in multus_is_available
    return self.kubernetes.multus_is_available()
  File "/var/lib/juju/agents/unit-du-0/charm/lib/charms/kubernetes_charm_libraries/v0/multus.py", line 580, in multus_is_available
    raise KubernetesMultusError(
charms.kubernetes_charm_libraries.v0.multus.KubernetesMultusError: Unexpected outcome when checking for Multus availability
unit-du-0: 11:47:11 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1
unit-du-0: 11:47:11 INFO juju.worker.uniter awaiting error resolution for "update-status" hook
unit-du-0: 11:47:16 INFO juju.worker.uniter awaiting error resolution for "update-status" hook
unit-du-0: 11:47:17 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 401 Unauthorized"
unit-du-0: 11:47:17 ERROR unit.du/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-du-0/charm/venv/lightkube/core/generic_client.py", line 235, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/juju/agents/unit-du-0/charm/venv/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-du-0/charm/lib/charms/kubernetes_charm_libraries/v0/multus.py", line 571, in multus_is_available
    list(
  File "/var/lib/juju/agents/unit-du-0/charm/venv/lightkube/core/generic_client.py", line 318, in list
    cont, chunk = self.handle_response("list", resp, br)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/lightkube/core/generic_client.py", line 251, in handle_response
    self.raise_for_status(resp)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/lightkube/core/generic_client.py", line 237, in raise_for_status
    raise transform_exception(e)
lightkube.core.exceptions.ApiError: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-du-0/charm/./src/charm.py", line 490, in <module>
    main(OAIRANDUOperator)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/__init__.py", line 343, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/_main.py", line 543, in main
    manager.run()
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/_main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/_main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/_main.py", line 134, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/framework.py", line 857, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-du-0/charm/./src/charm.py", line 161, in _configure
    if not self._kubernetes_multus.multus_is_available():
  File "/var/lib/juju/agents/unit-du-0/charm/lib/charms/kubernetes_charm_libraries/v0/multus.py", line 765, in multus_is_available
    return self.kubernetes.multus_is_available()
  File "/var/lib/juju/agents/unit-du-0/charm/lib/charms/kubernetes_charm_libraries/v0/multus.py", line 580, in multus_is_available
    raise KubernetesMultusError(
charms.kubernetes_charm_libraries.v0.multus.KubernetesMultusError: Unexpected outcome when checking for Multus availability
unit-du-0: 11:47:17 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1
unit-du-0: 11:47:17 INFO juju.worker.uniter awaiting error resolution for "update-status" hook
unit-du-0: 11:47:27 INFO juju.worker.uniter awaiting error resolution for "update-status" hook
unit-du-0: 11:47:28 INFO unit.du/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions "HTTP/1.1 401 Unauthorized"
unit-du-0: 11:47:28 ERROR unit.du/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-du-0/charm/venv/lightkube/core/generic_client.py", line 235, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/juju/agents/unit-du-0/charm/venv/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/ran/network-attachment-definitions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-du-0/charm/lib/charms/kubernetes_charm_libraries/v0/multus.py", line 571, in multus_is_available
    list(
  File "/var/lib/juju/agents/unit-du-0/charm/venv/lightkube/core/generic_client.py", line 318, in list
    cont, chunk = self.handle_response("list", resp, br)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/lightkube/core/generic_client.py", line 251, in handle_response
    self.raise_for_status(resp)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/lightkube/core/generic_client.py", line 237, in raise_for_status
    raise transform_exception(e)
lightkube.core.exceptions.ApiError: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-du-0/charm/./src/charm.py", line 490, in <module>
    main(OAIRANDUOperator)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/__init__.py", line 343, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/_main.py", line 543, in main
    manager.run()
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/_main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/_main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/_main.py", line 134, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/framework.py", line 857, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-du-0/charm/venv/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-du-0/charm/./src/charm.py", line 161, in _configure
    if not self._kubernetes_multus.multus_is_available():
  File "/var/lib/juju/agents/unit-du-0/charm/lib/charms/kubernetes_charm_libraries/v0/multus.py", line 765, in multus_is_available
    return self.kubernetes.multus_is_available()
  File "/var/lib/juju/agents/unit-du-0/charm/lib/charms/kubernetes_charm_libraries/v0/multus.py", line 580, in multus_is_available
    raise KubernetesMultusError(
charms.kubernetes_charm_libraries.v0.multus.KubernetesMultusError: Unexpected outcome when checking for Multus availability
unit-du-0: 11:47:29 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1
unit-du-0: 11:47:29 INFO juju.worker.uniter awaiting error resolution for "update-status" hook
unit-du-0: 11:47:37 INFO juju.worker.uniter awaiting error resolution for "update-status" hook
```

**Comment by Gmerold** [comment]
Fixed in https://github.com/canonical/kubernetes-charm-libraries/pull/73
